# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b6b1dd2fc6a806d46c05dfa3a77e867a773b6ed8579d9323d6d13dcfeee47ba683af5c9943392b21c56346f653692a1c06e8420dca8ad7f49f30e79498fd6d4

test:
  secret_key_base: e8e251fe7a18006a515702cb19d03753ea86357f6b430f115d47d4571bf0d5aa176d73d9e6409bd55a93636cf29c6df2ff389c14ab959521f4998a1cc5f43890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
